networks:
  mvp-backend-advanced:
    driver: bridge 

services:
  mysql-service:
    image: bitnami/mysql:latest
    container_name: database-mysql
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mvp-backend-advanced
    environment:
      MYSQL_ROOT_PASSWORD: 142536
      MYSQL_DATABASE: mvp2
      MYSQL_USER: app
      MYSQL_PASSWORD: app142536
  
  model-data-service:
    image: bitnami/python:latest
    container_name: application-python-data-model
    build: ./container-data-model
    networks:
      - mvp-backend-advanced
    ports:
      - "3001:3001"
    environment:
      APP_PORT: 3001

  loader-data-service:
    image: node:18
    container_name: application-nodejs-loader
    build: ./container-data-loader
    networks:
      - mvp-backend-advanced
    ports:
      - "3002:3002"
    environment:
      APP_PORT: 3002

  api-service:
    image: node:18
    container_name: application-nodejs-api
    build: ./container-api
    networks:
      - mvp-backend-advanced
    ports:
      - "3003:3003"
    environment:
      APP_PORT: 3003

  frontend-service:
    image: nginx:latest
    container_name: application-frontend
    build: ./container-frontend
    networks:
      - mvp-backend-advanced
    ports:
      - "3004:3004"
