networks:
  puc_mvp:
    driver: bridge 

services:
  mysql:
    container_name: mysql_container
    hostname: mysql_host
    build: ./mysql_container
    networks:
      - puc_mvp
    volumes:
      - mysql_data:/bitnami/mysql/data
    healthcheck:
      test: mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'
      interval: 10s
      timeout: 5s
      retries: 10
  
  model:
    container_name: model_container
    hostname: model_host
    build: ./model_container
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - puc_mvp

  loader:
    container_name: loader_container
    hostname: loader_host
    build: ./loader_container
    networks:
      - puc_mvp

  api:
    container_name: api_container
    hostname: api_host
    build: ./api_container
    networks:
      - puc_mvp
    ports:
      - "3002:3002"

  frontend:
    container_name: frontend_container
    hostname: frontend_host
    build: ./frontend_container
    networks:
      - puc_mvp
    ports:
      - "3003:3003"

volumes:
  mysql_data: